"""Friendly display names / translation keys for Zyxel entities.

Home Assistant resolves ``translation_key`` against
``translations/<lang>.json`` → ``entity.<platform>.<key>.name``.
Unknown dynamic fields fall back to a humanized English label.
"""
from __future__ import annotations

import re

_SLUG_RE = re.compile(r"[^a-z0-9]+")
_CAMEL_RE = re.compile(r"(?<=[a-z0-9])(?=[A-Z])")

# Prefixes that add useful context in fallback names (English).
_PREFIX_LABELS = {
    "cellintfinfo": "Cellular",
    "cellintfsimfinfo": "SIM",
    "cellintfzynrnsainfo": "NSA",
    "cellintfzyippassthruinfo": "Passthrough",
    "wwanstatsinfo": "WWAN",
    "deviceinfo": "Device",
    "processstatus": "",
    "memorystatus": "Memory",
    "systeminfo": "System",
    "gponinfo": "GPON",
    "gponstatsinfo": "GPON",
    "firewallinfo": "Firewall",
    "lanportinfo": "LAN port",
    "meshinfo": "Mesh",
    "dhcp4serpoolinfo": "DHCP",
    "stbvendorid": "STB",
    "waninfo": "WAN",
    "one_connect": "One Connect",
    "cellular": "",
    "cardpage": "",
    "device": "",
    "traffic": "",
    "lan": "",
}


def field_translation_key(identity: str) -> str:
    """Stable translation key for a sensor identity / unique_id suffix."""
    slug = _SLUG_RE.sub("_", identity.lower()).strip("_")
    return f"f_{slug}"


def _humanize_token(token: str) -> str:
    text = token
    if text.upper().startswith("X_ZYXEL_"):
        text = text[8:]
    text = text.replace("_", " ")
    text = _CAMEL_RE.sub(" ", text)
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return token
    return text[0].upper() + text[1:]


def friendly_fallback_name(identity: str) -> str:
    """English humanized label when no translation entry exists."""
    parts = identity.split(".")
    leaf = _humanize_token(parts[-1])
    if len(parts) == 1:
        return leaf

    # traffic.br0.BytesSent or br0.BytesSent
    if parts[0] == "traffic" and len(parts) == 3:
        return f"{leaf} ({parts[1]})"
    if re.fullmatch(r"br0|ccmni\d+|eth0(?:\.\d+)?", parts[0]) and len(parts) == 2:
        return f"{leaf} ({parts[0]})"

    prefix_key = parts[0].lower()
    prefix = _PREFIX_LABELS.get(prefix_key)
    if prefix is None:
        prefix = _humanize_token(parts[0])
    if prefix and not leaf.lower().startswith(prefix.lower()):
        return f"{prefix}: {leaf}"
    return leaf

KNOWN_TRANSLATION_KEYS = frozenset({
    "address_source",
    "band",
    "bytes_received",
    "bytes_sent",
    "connected",
    "connected_devices",
    "connected_duration",
    "connection_type",
    "device_type",
    "downlink_rate",
    "f_aliasipaddress",
    "f_antenna_status",
    "f_br0_broadcastpacketsreceived",
    "f_br0_broadcastpacketssent",
    "f_br0_bytesreceived",
    "f_br0_bytessent",
    "f_br0_discardpacketsreceived",
    "f_br0_discardpacketssent",
    "f_br0_errorsreceived",
    "f_br0_errorssent",
    "f_br0_multicastpacketsreceived",
    "f_br0_multicastpacketssent",
    "f_br0_packetsreceived",
    "f_br0_packetssent",
    "f_br0_unicastpacketsreceived",
    "f_br0_unicastpacketssent",
    "f_br0_unknownprotopacketsreceived",
    "f_ccmni1_broadcastpacketsreceived",
    "f_ccmni1_broadcastpacketssent",
    "f_ccmni1_bytesreceived",
    "f_ccmni1_bytessent",
    "f_ccmni1_discardpacketsreceived",
    "f_ccmni1_discardpacketssent",
    "f_ccmni1_errorsreceived",
    "f_ccmni1_errorssent",
    "f_ccmni1_multicastpacketsreceived",
    "f_ccmni1_multicastpacketssent",
    "f_ccmni1_packetsreceived",
    "f_ccmni1_packetssent",
    "f_ccmni1_unicastpacketsreceived",
    "f_ccmni1_unicastpacketssent",
    "f_ccmni1_unknownprotopacketsreceived",
    "f_ccmni2_broadcastpacketsreceived",
    "f_ccmni2_broadcastpacketssent",
    "f_ccmni2_bytesreceived",
    "f_ccmni2_bytessent",
    "f_ccmni2_discardpacketsreceived",
    "f_ccmni2_discardpacketssent",
    "f_ccmni2_errorsreceived",
    "f_ccmni2_errorssent",
    "f_ccmni2_multicastpacketsreceived",
    "f_ccmni2_multicastpacketssent",
    "f_ccmni2_packetsreceived",
    "f_ccmni2_packetssent",
    "f_ccmni2_unicastpacketsreceived",
    "f_ccmni2_unicastpacketssent",
    "f_ccmni2_unknownprotopacketsreceived",
    "f_cell_roaming_enable",
    "f_cell_roaming_status",
    "f_cellintfinfo_alias",
    "f_cellintfinfo_availablenetworks",
    "f_cellintfinfo_currentaccesstechnology",
    "f_cellintfinfo_downstreammaxbitrate",
    "f_cellintfinfo_enable",
    "f_cellintfinfo_imei",
    "f_cellintfinfo_lastchange",
    "f_cellintfinfo_lowerlayers",
    "f_cellintfinfo_name",
    "f_cellintfinfo_networkinuse",
    "f_cellintfinfo_networkrequested",
    "f_cellintfinfo_preferredaccesstechnology",
    "f_cellintfinfo_rssi",
    "f_cellintfinfo_status",
    "f_cellintfinfo_supportedaccesstechnologies",
    "f_cellintfinfo_upstream",
    "f_cellintfinfo_upstreammaxbitrate",
    "f_cellintfinfo_x_zyxel_bsic",
    "f_cellintfinfo_x_zyxel_cellid",
    "f_cellintfinfo_x_zyxel_cpichecno",
    "f_cellintfinfo_x_zyxel_cpichrscp",
    "f_cellintfinfo_x_zyxel_cqi",
    "f_cellintfinfo_x_zyxel_currentband",
    "f_cellintfinfo_x_zyxel_downlinkbandwidth",
    "f_cellintfinfo_x_zyxel_hw_nat_enable",
    "f_cellintfinfo_x_zyxel_lac",
    "f_cellintfinfo_x_zyxel_mcs",
    "f_cellintfinfo_x_zyxel_modulesoftwareversion",
    "f_cellintfinfo_x_zyxel_phycellid",
    "f_cellintfinfo_x_zyxel_pmi",
    "f_cellintfinfo_x_zyxel_preferredbands",
    "f_cellintfinfo_x_zyxel_primaryscramblingcode",
    "f_cellintfinfo_x_zyxel_rac",
    "f_cellintfinfo_x_zyxel_rfcn",
    "f_cellintfinfo_x_zyxel_ri",
    "f_cellintfinfo_x_zyxel_rsrp",
    "f_cellintfinfo_x_zyxel_rsrq",
    "f_cellintfinfo_x_zyxel_sinr",
    "f_cellintfinfo_x_zyxel_supportedbands",
    "f_cellintfinfo_x_zyxel_tac",
    "f_cellintfinfo_x_zyxel_uplinkbandwidth",
    "f_cellintfsimfinfo_iccid",
    "f_cellintfsimfinfo_imsi",
    "f_cellintfsimfinfo_msisdn",
    "f_cellintfsimfinfo_pin",
    "f_cellintfsimfinfo_pincheck",
    "f_cellintfsimfinfo_status",
    "f_cellintfsimfinfo_x_zyxel_autounlockpin",
    "f_cellintfsimfinfo_x_zyxel_newpin",
    "f_cellintfsimfinfo_x_zyxel_pin_protection",
    "f_cellintfsimfinfo_x_zyxel_pin_remainingattempts",
    "f_cellintfsimfinfo_x_zyxel_pin_state",
    "f_cellintfsimfinfo_x_zyxel_puk",
    "f_cellintfsimfinfo_x_zyxel_puk_remainingattempts",
    "f_cellintfzyippassthruinfo_connectionmode",
    "f_cellintfzyippassthruinfo_enable",
    "f_cellintfzyippassthruinfo_macaddress",
    "f_cellintfzynrnsainfo_band",
    "f_cellintfzynrnsainfo_downlinkbandwidth",
    "f_cellintfzynrnsainfo_enable",
    "f_cellintfzynrnsainfo_mcc",
    "f_cellintfzynrnsainfo_mnc",
    "f_cellintfzynrnsainfo_phycellid",
    "f_cellintfzynrnsainfo_rfcn",
    "f_cellintfzynrnsainfo_rsrp",
    "f_cellintfzynrnsainfo_rsrq",
    "f_cellintfzynrnsainfo_rssi",
    "f_cellintfzynrnsainfo_sinr",
    "f_cellintfzynrnsainfo_uplinkbandwidth",
    "f_cellular_antenna_status",
    "f_cellular_cell_roaming_enable",
    "f_cellular_cell_roaming_status",
    "f_cellular_intf_bsic",
    "f_cellular_intf_cell_id",
    "f_cellular_intf_cqi",
    "f_cellular_intf_current_access_technology",
    "f_cellular_intf_current_band",
    "f_cellular_intf_downlink_bandwidth",
    "f_cellular_intf_ecno",
    "f_cellular_intf_imei",
    "f_cellular_intf_lac",
    "f_cellular_intf_mcs",
    "f_cellular_intf_module_software_version",
    "f_cellular_intf_network_in_use",
    "f_cellular_intf_phycell_id",
    "f_cellular_intf_pmi",
    "f_cellular_intf_rac",
    "f_cellular_intf_rfcn",
    "f_cellular_intf_ri",
    "f_cellular_intf_rscp",
    "f_cellular_intf_rsrp",
    "f_cellular_intf_rsrq",
    "f_cellular_intf_rssi",
    "f_cellular_intf_sinr",
    "f_cellular_intf_status",
    "f_cellular_intf_supported_bands",
    "f_cellular_intf_tac",
    "f_cellular_intf_uplink_bandwidth",
    "f_cellular_nsa_band",
    "f_cellular_nsa_downlinkbandwidth",
    "f_cellular_nsa_enable",
    "f_cellular_nsa_mcc",
    "f_cellular_nsa_mnc",
    "f_cellular_nsa_phycellid",
    "f_cellular_nsa_rfcn",
    "f_cellular_nsa_rsrp",
    "f_cellular_nsa_rsrq",
    "f_cellular_nsa_rssi",
    "f_cellular_nsa_sinr",
    "f_cellular_nsa_uplinkbandwidth",
    "f_cellular_passthru_enable",
    "f_cellular_passthru_macaddr",
    "f_cellular_passthru_mode",
    "f_cellular_usim_iccid",
    "f_cellular_usim_imsi",
    "f_cellular_usim_pin_protection",
    "f_cellular_usim_pin_remaining_attempts",
    "f_cellular_usim_status",
    "f_connected_clients",
    "f_controller_mode",
    "f_currole",
    "f_deviceinfo_additionalhardwareversion",
    "f_deviceinfo_additionalsoftwareversion",
    "f_deviceinfo_connectivity",
    "f_deviceinfo_description",
    "f_deviceinfo_enable",
    "f_deviceinfo_firstusedate",
    "f_deviceinfo_fixmanufactureroui",
    "f_deviceinfo_hardwareversion",
    "f_deviceinfo_internalsoftwareversion",
    "f_deviceinfo_locationnumberofentries",
    "f_deviceinfo_manufacturer",
    "f_deviceinfo_manufactureroui",
    "f_deviceinfo_modelname",
    "f_deviceinfo_modulesoftwareversion",
    "f_deviceinfo_ncc_qr",
    "f_deviceinfo_nebulaclaimreason",
    "f_deviceinfo_nebulaclaimstatus",
    "f_deviceinfo_nebulacloudreason",
    "f_deviceinfo_nebulacloudstatus",
    "f_deviceinfo_nebulantpreason",
    "f_deviceinfo_nebulantpstatus",
    "f_deviceinfo_packageversion",
    "f_deviceinfo_processornumberofentries",
    "f_deviceinfo_productclass",
    "f_deviceinfo_provisioningcode",
    "f_deviceinfo_serialnumber",
    "f_deviceinfo_softwareversion",
    "f_deviceinfo_supporteddatamodelnumberofentries",
    "f_deviceinfo_uptime",
    "f_deviceinfo_vendorconfigfilenumberofentries",
    "f_deviceinfo_vendorlogfilenumberofentries",
    "f_deviceinfo_x_zyxel_provisioningcodeintf",
    "f_deviceinfo_x_zyxel_provisioningkey",
    "f_deviceinfo_x_zyxel_softwarearchitecture",
    "f_dhcp4serpoolinfo_alias",
    "f_dhcp4serpoolinfo_chaddr",
    "f_dhcp4serpoolinfo_chaddrexclude",
    "f_dhcp4serpoolinfo_chaddrmask",
    "f_dhcp4serpoolinfo_clientid",
    "f_dhcp4serpoolinfo_clientidexclude",
    "f_dhcp4serpoolinfo_clientnumberofentries",
    "f_dhcp4serpoolinfo_dnsservers",
    "f_dhcp4serpoolinfo_domainname",
    "f_dhcp4serpoolinfo_enable",
    "f_dhcp4serpoolinfo_interface",
    "f_dhcp4serpoolinfo_iprouters",
    "f_dhcp4serpoolinfo_leasetime",
    "f_dhcp4serpoolinfo_maxaddress",
    "f_dhcp4serpoolinfo_minaddress",
    "f_dhcp4serpoolinfo_optionnumberofentries",
    "f_dhcp4serpoolinfo_order",
    "f_dhcp4serpoolinfo_reservedaddresses",
    "f_dhcp4serpoolinfo_staticaddressnumberofentries",
    "f_dhcp4serpoolinfo_status",
    "f_dhcp4serpoolinfo_subnetmask",
    "f_dhcp4serpoolinfo_userclassid",
    "f_dhcp4serpoolinfo_vendorclassid",
    "f_dhcp4serpoolinfo_vendorclassidexclude",
    "f_dhcp4serpoolinfo_vendorclassidmode",
    "f_dhcp4serpoolinfo_x_zyxel_autoreservelanip",
    "f_dhcp4serpoolinfo_x_zyxel_dns_type",
    "f_dhcp4serpoolinfo_x_zyxel_serverconfigurable",
    "f_dhcp4serpoolinfo_x_zyxel_setenable",
    "f_dhcp4serpoolinfo_x_zyxel_stb_prcode",
    "f_dhcp4serpoolinfo_x_zyxel_stb_prcode_subcode",
    "f_dhcp4serpoolinfo_x_zyxel_stb_url",
    "f_dhcp4serpoolinfo_x_zyxel_stb_url_subcode",
    "f_dhcp4serpoolinfo_x_zyxel_stb_vendorid",
    "f_dhcp_autoreservelanip",
    "f_dhcp_leasetime",
    "f_dhcp_maxaddress",
    "f_dhcp_minaddress",
    "f_dhcptype",
    "f_dns_type",
    "f_dnsqueryscenario",
    "f_dnsservers",
    "f_easymeshenable",
    "f_enablealias",
    "f_enabledhcp",
    "f_eth0_2_broadcastpacketsreceived",
    "f_eth0_2_broadcastpacketssent",
    "f_eth0_2_bytesreceived",
    "f_eth0_2_bytessent",
    "f_eth0_2_discardpacketsreceived",
    "f_eth0_2_discardpacketssent",
    "f_eth0_2_errorsreceived",
    "f_eth0_2_errorssent",
    "f_eth0_2_multicastpacketsreceived",
    "f_eth0_2_multicastpacketssent",
    "f_eth0_2_packetsreceived",
    "f_eth0_2_packetssent",
    "f_eth0_2_unicastpacketsreceived",
    "f_eth0_2_unicastpacketssent",
    "f_eth0_2_unknownprotopacketsreceived",
    "f_firewallinfo_advancedlevel",
    "f_firewallinfo_chainnumberofentries",
    "f_firewallinfo_config",
    "f_firewallinfo_enable",
    "f_firewallinfo_ipv4_enable",
    "f_firewallinfo_ipv6_enable",
    "f_firewallinfo_lastchange",
    "f_firewallinfo_levelnumberofentries",
    "f_firewallinfo_type",
    "f_firewallinfo_version",
    "f_firewallinfo_x_zyxel_defaultconfig",
    "f_firewallinfo_x_zyxel_denyping",
    "f_firewallinfo_x_zyxel_dos_enable",
    "f_gponinfo_connectivitycap",
    "f_gponinfo_emergencystate",
    "f_gponinfo_enhancedpsk",
    "f_gponinfo_equipmentid",
    "f_gponinfo_extendedtclayer",
    "f_gponinfo_maxports",
    "f_gponinfo_modelname",
    "f_gponinfo_omccversion",
    "f_gponinfo_onusurvivaltime",
    "f_gponinfo_onutype",
    "f_gponinfo_operationalstate",
    "f_gponinfo_password",
    "f_gponinfo_portlist1",
    "f_gponinfo_qosconfflex",
    "f_gponinfo_rxpower",
    "f_gponinfo_securitycap",
    "f_gponinfo_securitymode",
    "f_gponinfo_serialnumber",
    "f_gponinfo_temperature",
    "f_gponinfo_tmoption",
    "f_gponinfo_totalgemportnum",
    "f_gponinfo_totalpqnum",
    "f_gponinfo_totaltsnum",
    "f_gponinfo_txpower",
    "f_gponinfo_vendorid",
    "f_gponinfo_vendorprocode",
    "f_gponinfo_version",
    "f_gponinfo_voltage",
    "f_gponstatsinfo_rxpowersignal",
    "f_gponstatsinfo_sfp_model",
    "f_gponstatsinfo_sfp_presence",
    "f_gponstatsinfo_sfp_serial",
    "f_gponstatsinfo_sfp_vendor",
    "f_gponstatsinfo_temperature",
    "f_gponstatsinfo_txpowersignal",
    "f_guestssidenable",
    "f_igmpsnoopingmode",
    "f_intf_bsic",
    "f_intf_cell_id",
    "f_intf_cqi",
    "f_intf_current_access_technology",
    "f_intf_current_band",
    "f_intf_downlink_bandwidth",
    "f_intf_ecno",
    "f_intf_imei",
    "f_intf_lac",
    "f_intf_mcs",
    "f_intf_module_software_version",
    "f_intf_network_in_use",
    "f_intf_phycell_id",
    "f_intf_pmi",
    "f_intf_rac",
    "f_intf_rfcn",
    "f_intf_ri",
    "f_intf_rscp",
    "f_intf_rsrp",
    "f_intf_rsrq",
    "f_intf_rssi",
    "f_intf_sinr",
    "f_intf_status",
    "f_intf_supported_bands",
    "f_intf_tac",
    "f_intf_uplink_bandwidth",
    "f_ipaddress",
    "f_ipv6_dnsassign",
    "f_ipv6_dnsserver1",
    "f_ipv6_dnsserver2",
    "f_ipv6_dnsserver3",
    "f_ipv6_identifiertype",
    "f_ipv6_lanaddrassign",
    "f_ipv6_lanenable",
    "f_ipv6_linklocaladdresstype",
    "f_ipv6_prefixtype",
    "f_ipv6_prefixwan",
    "f_lanportinfo_ethportexist",
    "f_lanportinfo_lanmac",
    "f_maxmtusize",
    "f_memorystatus_free",
    "f_memorystatus_total",
    "f_memoryusage",
    "f_memusage",
    "f_meshinfo_automode",
    "f_meshinfo_band",
    "f_meshinfo_controller",
    "f_meshinfo_dataelementsenable",
    "f_meshinfo_enable",
    "f_meshinfo_role",
    "f_mldsnoopingmode",
    "f_name",
    "f_nsa_band",
    "f_nsa_downlinkbandwidth",
    "f_nsa_enable",
    "f_nsa_mcc",
    "f_nsa_mnc",
    "f_nsa_phycellid",
    "f_nsa_rfcn",
    "f_nsa_rsrp",
    "f_nsa_rsrq",
    "f_nsa_rssi",
    "f_nsa_sinr",
    "f_nsa_uplinkbandwidth",
    "f_one_connect_one_connect_enable",
    "f_partctlnum",
    "f_passthru_enable",
    "f_passthru_macaddr",
    "f_passthru_mode",
    "f_processstatus_cpuusage",
    "f_processstatus_processnumberofentries",
    "f_reboot",
    "f_startup_time",
    "f_stbvendorid_stbvendorid1",
    "f_stbvendorid_stbvendorid2",
    "f_stbvendorid_stbvendorid3",
    "f_stbvendorid_stbvendorid4",
    "f_stbvendorid_stbvendorid5",
    "f_subnetmask",
    "f_systeminfo_cbt_accountreset",
    "f_systeminfo_contact",
    "f_systeminfo_domainname",
    "f_systeminfo_hostname",
    "f_systeminfo_ishostnamemodify",
    "f_systeminfo_location",
    "f_systeminfo_onlineguide",
    "f_systeminfo_x_zyxel_loginbanner",
    "f_traffic_br0_broadcastpacketsreceived",
    "f_traffic_br0_broadcastpacketssent",
    "f_traffic_br0_bytesreceived",
    "f_traffic_br0_bytessent",
    "f_traffic_br0_discardpacketsreceived",
    "f_traffic_br0_discardpacketssent",
    "f_traffic_br0_errorsreceived",
    "f_traffic_br0_errorssent",
    "f_traffic_br0_multicastpacketsreceived",
    "f_traffic_br0_multicastpacketssent",
    "f_traffic_br0_packetsreceived",
    "f_traffic_br0_packetssent",
    "f_traffic_br0_unicastpacketsreceived",
    "f_traffic_br0_unicastpacketssent",
    "f_traffic_br0_unknownprotopacketsreceived",
    "f_traffic_ccmni1_broadcastpacketsreceived",
    "f_traffic_ccmni1_broadcastpacketssent",
    "f_traffic_ccmni1_bytesreceived",
    "f_traffic_ccmni1_bytessent",
    "f_traffic_ccmni1_discardpacketsreceived",
    "f_traffic_ccmni1_discardpacketssent",
    "f_traffic_ccmni1_errorsreceived",
    "f_traffic_ccmni1_errorssent",
    "f_traffic_ccmni1_multicastpacketsreceived",
    "f_traffic_ccmni1_multicastpacketssent",
    "f_traffic_ccmni1_packetsreceived",
    "f_traffic_ccmni1_packetssent",
    "f_traffic_ccmni1_unicastpacketsreceived",
    "f_traffic_ccmni1_unicastpacketssent",
    "f_traffic_ccmni1_unknownprotopacketsreceived",
    "f_traffic_ccmni2_broadcastpacketsreceived",
    "f_traffic_ccmni2_broadcastpacketssent",
    "f_traffic_ccmni2_bytesreceived",
    "f_traffic_ccmni2_bytessent",
    "f_traffic_ccmni2_discardpacketsreceived",
    "f_traffic_ccmni2_discardpacketssent",
    "f_traffic_ccmni2_errorsreceived",
    "f_traffic_ccmni2_errorssent",
    "f_traffic_ccmni2_multicastpacketsreceived",
    "f_traffic_ccmni2_multicastpacketssent",
    "f_traffic_ccmni2_packetsreceived",
    "f_traffic_ccmni2_packetssent",
    "f_traffic_ccmni2_unicastpacketsreceived",
    "f_traffic_ccmni2_unicastpacketssent",
    "f_traffic_ccmni2_unknownprotopacketsreceived",
    "f_traffic_eth0_2_broadcastpacketsreceived",
    "f_traffic_eth0_2_broadcastpacketssent",
    "f_traffic_eth0_2_bytesreceived",
    "f_traffic_eth0_2_bytessent",
    "f_traffic_eth0_2_discardpacketsreceived",
    "f_traffic_eth0_2_discardpacketssent",
    "f_traffic_eth0_2_errorsreceived",
    "f_traffic_eth0_2_errorssent",
    "f_traffic_eth0_2_multicastpacketsreceived",
    "f_traffic_eth0_2_multicastpacketssent",
    "f_traffic_eth0_2_packetsreceived",
    "f_traffic_eth0_2_packetssent",
    "f_traffic_eth0_2_unicastpacketsreceived",
    "f_traffic_eth0_2_unicastpacketssent",
    "f_traffic_eth0_2_unknownprotopacketsreceived",
    "f_uptime",
    "f_usim_iccid",
    "f_usim_imsi",
    "f_usim_pin_protection",
    "f_usim_pin_remaining_attempts",
    "f_usim_status",
    "f_waninfo_wanifaceexist",
    "f_waninfo_wanstatus",
    "f_waninfo_wantype",
    "f_wwanstatsinfo_connectionuptime",
    "f_wwanstatsinfo_fwversion",
    "f_wwanstatsinfo_manufacturer",
    "f_wwanstatsinfo_model",
    "f_wwanstatsinfo_remainingpin",
    "f_wwanstatsinfo_serviceprovider",
    "f_wwanstatsinfo_signalstrength",
    "f_wwanstatsinfo_simimsi",
    "f_x_zyxel_temperature_ambient",
    "f_x_zyxel_temperature_cpu0",
    "f_x_zyxel_temperature_sdx",
    "ip_address",
    "link_rate",
    "memory_usage",
    "network",
    "reboot",
    "rssi",
    "signal_quality",
    "snr",
    "ssid",
    "startup_time",
    "uplink_rate",
    "wifi_standard",
})
